# Generated by Django 3.2.3 on 2021-06-28 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_cashback_all'),
        ('product', '0002_auto_20210628_1337'),
        ('cashback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashback',
            name='percent',
        ),
        migrations.AddField(
            model_name='cashback',
            name='percent_products',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Процент продуктов'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CashAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_add', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cashback.cashback', verbose_name='кэш')),
                ('total_cash', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client', verbose_name='Общий Кэшбек')),
            ],
        ),
    ]
