# Generated by Django 3.2.3 on 2021-06-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashback', '0002_auto_20210628_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashback',
            name='percent',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
