# Generated by Django 3.2.3 on 2021-07-03 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashback', '0003_cashback_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashback',
            name='percent',
        ),
        migrations.RemoveField(
            model_name='cashback',
            name='percent_products',
        ),
    ]
