# Generated by Django 3.2.3 on 2021-07-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_auto_20210628_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleproduct',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=9, verbose_name='Общая цена'),
        ),
    ]
