# Generated by Django 3.2.3 on 2021-07-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_alter_saleproduct_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleproduct',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, verbose_name='Общая цена'),
        ),
    ]
